name: ServiceNow Ticket Workflow

on:
  workflow_dispatch:
    inputs:
      ticket_number:
        required: true
      instance_url:
        required: true

jobs:
  run-ticket-job:
    runs-on: ubuntu-latest
    env:
      INSTANCE_URL: ${{ github.event.inputs.instance_url }}
      TICKET_NUMBER: ${{ github.event.inputs.ticket_number }}
    steps:
      - name: Display ticket number
        run: echo "Ticket: $TICKET_NUMBER"

      - name: Call script or API
        run: |
          echo "Here you can execute your GitHub script or call APIs"
